//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodMedicalApp.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalEntities : DbContext
    {
        public MedicalEntities()
            : base("name=MedicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoctorEntity> DoctorEntities { get; set; }
        public virtual DbSet<MedicineEntity> MedicineEntities { get; set; }
        public virtual DbSet<OperationEntity> OperationEntities { get; set; }
        public virtual DbSet<PatientEntity> PatientEntities { get; set; }
        public virtual DbSet<RoomEntity> RoomEntities { get; set; }
        public virtual DbSet<TreatmentEntity> TreatmentEntities { get; set; }
        public virtual DbSet<TreatmentReportEntity> TreatmentReportEntities { get; set; }
        public virtual DbSet<TypeMedicineEntity> TypeMedicineEntities { get; set; }
        public virtual DbSet<TypeOperationEntity> TypeOperationEntities { get; set; }
    }
}
